//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use cms_core::{
    domain::{SelectOptionItem, SelectValueEnum},
    utils::time,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mate_kind")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub editor_type: String,
    pub editor_id: i64,
    pub app_id: i64,
    pub name: String,
    pub title: String,
    pub max_level: i8,
    pub description: String,
    pub icon: String,
    pub is_multiple: bool,
    pub sort: i16,
    pub is_enabled: bool,
    pub is_deleted: bool,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id"
    )]
    App,

    #[sea_orm(has_many = "super::item::Entity")]
    Item,

    #[sea_orm(has_many = "super::morph::Entity")]
    Morph,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Item.def()
    }
}

impl Related<super::morph::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Morph.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn created_time(&self) -> String {
        time::to_db_time(&self.created_at)
    }

    pub fn updated_time(&self) -> String {
        time::to_db_time(&self.updated_at)
    }
}

impl Into<SelectOptionItem> for Model {
    fn into(self) -> SelectOptionItem {
        SelectOptionItem {
            label: self.title,
            value: SelectValueEnum::BigNum(self.id),
            disabled: Some(!self.is_enabled),
            alias: Some(vec![self.name]),
            group: Some(self.app_id.to_string()),
            children: None,
            ..Default::default()
        }
    }
}

impl Into<SelectOptionItem> for &Model {
    fn into(self) -> SelectOptionItem {
        SelectOptionItem {
            label: self.title.clone(),
            value: SelectValueEnum::BigNum(self.id),
            disabled: Some(!self.is_enabled),
            alias: Some(vec![self.name.clone()]),
            group: Some(self.app_id.to_string()),
            children: None,
            ..Default::default()
        }
    }
}
