use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(CategoryItem::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CategoryItem::Id)
                            .big_integer()
                            .primary_key()
                            .auto_increment()
                            .comment("ID"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::EditorType)
                            .string_len(10)
                            .not_null()
                            .default("system")
                            .comment("编辑类型"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::EditorId)
                            .big_integer()
                            .not_null()
                            .default(0)
                            .comment("编辑ID"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::ItemType)
                            .string_len(30)
                            .not_null()
                            .default("")
                            .comment("分类类型"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Name)
                            .string_len(30)
                            .not_null()
                            .default("system")
                            .comment("Name"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Title)
                            .string_len(20)
                            .not_null()
                            .default("system")
                            .comment("标题"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Description)
                            .string_len(200)
                            .not_null()
                            .default("")
                            .comment("摘要"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Introduction)
                            .text()
                            .comment("简介"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::IconPath)
                            .string_len(150)
                            .not_null()
                            .default("")
                            .comment("图标"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::PcDetailPath)
                            .string_len(150)
                            .not_null()
                            .default("")
                            .comment("PC详情封面图"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::WapDetailPath)
                            .string_len(150)
                            .not_null()
                            .default("")
                            .comment("WAP详情封面图"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::ParentId)
                            .big_integer()
                            .not_null()
                            .default(0)
                            .comment("父级ID"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::IsDirectory)
                            .boolean()
                            .not_null()
                            .default(false)
                            .comment("是否为目录"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Level)
                            .tiny_integer()
                            .not_null()
                            .default(0)
                            .comment("层级"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Path)
                            .string_len(20)
                            .not_null()
                            .default("")
                            .comment("路径"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Extends)
                            .json()
                            .comment("扩展信息"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::Sort)
                            .small_integer()
                            .not_null()
                            .default(99)
                            .comment("排序编号"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::IsEnabled)
                            .boolean()
                            .not_null()
                            .default(true)
                            .comment("是否启用"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false)
                            .comment("是否删除"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::CreatedAt)
                            .date_time()
                            .not_null()
                            .comment("创建时间"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::UpdatedAt)
                            .date_time()
                            .not_null()
                            .comment("更新时间"),
                    )
                    .col(
                        ColumnDef::new(CategoryItem::DeletedAt)
                            .date_time()
                            .comment("删除时间"),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("categories_idx_by_itype")
                    .table(CategoryItem::Table)
                    .col(CategoryItem::ItemType)
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(CategoryItem::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum CategoryItem {
    #[sea_orm(iden = "category_items")]
    Table,
    Id,
    EditorType,
    EditorId,
    ItemType,
    Name,
    Title,
    Description,
    Introduction,
    IconPath,
    PcDetailPath,
    WapDetailPath,
    ParentId,
    IsDirectory,
    Level,
    Path,
    Extends,
    Sort,
    IsEnabled,
    IsDeleted,
    DeletedAt,
    CreatedAt,
    UpdatedAt,
}
