use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Replace the sample below with your own migration scripts
        manager
            .create_table(
                Table::create()
                    .table(MateApp::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MateApp::Id)
                            .big_integer()
                            .primary_key()
                            .auto_increment()
                            .comment("ID"),
                    )
                    .col(
                        ColumnDef::new(MateApp::EditorType)
                            .string_len(10)
                            .not_null()
                            .default("system")
                            .comment("编辑类型"),
                    )
                    .col(
                        ColumnDef::new(MateApp::EditorId)
                            .big_integer()
                            .not_null()
                            .default(0)
                            .comment("编辑ID"),
                    )
                    .col(
                        ColumnDef::new(MateApp::Name)
                            .string_len(30)
                            .not_null()
                            .default("")
                            .comment("名称"),
                    )
                    .col(
                        ColumnDef::new(MateApp::Title)
                            .string_len(30)
                            .not_null()
                            .default("")
                            .comment("标题"),
                    )
                    .col(
                        ColumnDef::new(MateApp::Description)
                            .string_len(200)
                            .not_null()
                            .default("")
                            .comment("描述"),
                    )
                    .col(
                        ColumnDef::new(MateApp::Icon)
                            .string_len(50)
                            .not_null()
                            .default("")
                            .comment("图标"),
                    )
                    .col(
                        ColumnDef::new(MateApp::Sort)
                            .small_integer()
                            .not_null()
                            .default(99)
                            .comment("排序编号"),
                    )
                    .col(
                        ColumnDef::new(MateApp::IsEnabled)
                            .boolean()
                            .not_null()
                            .default(true)
                            .comment("是否启用"),
                    )
                    .col(
                        ColumnDef::new(MateApp::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false)
                            .comment("是否删除"),
                    )
                    .col(
                        ColumnDef::new(MateApp::CreatedAt)
                            .date_time()
                            .not_null()
                            .comment("创建时间"),
                    )
                    .col(
                        ColumnDef::new(MateApp::UpdatedAt)
                            .date_time()
                            .not_null()
                            .comment("更新时间"),
                    )
                    .col(
                        ColumnDef::new(MateApp::DeletedAt)
                            .date_time()
                            .comment("删除时间"),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(MateApp::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum MateApp {
    #[sea_orm(iden = "mate_apps")]
    Table,
    Id,
    EditorType,
    EditorId,
    Name,
    Title,
    Description,
    Icon,
    Sort,
    IsEnabled,
    IsDeleted,
    DeletedAt,
    CreatedAt,
    UpdatedAt,
}
