//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod auth_certificate;
pub mod category_item;
pub mod mate_item;
pub mod mate_kind;
pub mod mate_module;
pub mod mate_morphable;
pub mod user;
pub mod user_detail;
pub mod user_login;
