//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod auth_certificates;
pub mod mate_apps;
pub mod mate_items;
pub mod mate_kinds;
pub mod mate_morphes;
pub mod user_details;
pub mod user_logins;
pub mod users;
