//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mate_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub editor_type: String,
    pub editor_id: i64,
    pub app_id: i64,
    pub kind_id: i64,
    pub name: String,
    pub title: String,
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub introduction: Option<String>,
    pub icon: String,
    pub pc_detail_path: String,
    pub wap_detail_path: String,
    pub parent_id: i64,
    pub level: i32,
    pub is_directory: bool,
    pub path: String,
    pub extends: Option<Json>,
    pub sort: i16,
    pub is_enabled: bool,
    pub is_deleted: bool,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
