//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::auth_certificate::Entity as AuthCertificate;
pub use super::category_item::Entity as CategoryItem;
pub use super::user::Entity as User;
pub use super::user_detail::Entity as UserDetail;
pub use super::user_login::Entity as UserLogin;
