//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::auth_certificates::Entity as AuthCertificates;
pub use super::mate_apps::Entity as MateApps;
pub use super::mate_items::Entity as MateItems;
pub use super::mate_kinds::Entity as MateKinds;
pub use super::mate_morphes::Entity as MateMorphes;
pub use super::user_details::Entity as UserDetails;
pub use super::user_logins::Entity as UserLogins;
pub use super::users::Entity as Users;
