//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub editor_type: String,
    pub editor_id: i64,
    pub no: String,
    pub name: String,
    pub realname: String,
    pub nickname: String,
    pub user_type: String,
    pub gender: i8,
    pub phone: String,
    pub avatar_path: String,
    pub email: String,
    pub data_source_id: i64,
    pub password: String,
    pub old_password: String,
    pub salt: String,
    pub password_modified_at: Option<DateTime>,
    pub attempted_times: i8,
    pub last_attempted_at: Option<DateTime>,
    pub last_login_id: i64,
    pub last_login_at: Option<DateTime>,
    pub is_authed: i8,
    pub is_enabled: i8,
    pub is_test: i8,
    pub is_deleted: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
